import bcrypt from "bcrypt";
import { v2 as cloudinary } from "cloudinary";
import crypto from "crypto";
import express from "express";
import rateLimiter from "express-rate-limit";
import fs from "fs";
import { StatusCodes } from "http-status-codes";
import jwt from "jsonwebtoken";
import moment from "moment-timezone";
import mongoose from "mongoose";
import nodemailer from "nodemailer";
import qs from "qs";
import slugify from "slugify";
import response from "./helpers/Response.js";
import * as userHelper from "./helpers/userHelper.js";
import { hashPassword } from "./helpers/userHelper.js";
import * as middleware from "./middleware/Auth.js";
import * as models from "./models/index.js";
import { appErr } from "./utils/appErr.js";

// Add the modules to the global object
global.bcrypt = bcrypt;
global.jwt = jwt;
global.nodemailer = nodemailer;
global.crypto = crypto;
global.express = express;
global.mongoose = mongoose;
global.moment = moment;
global.qs = qs;
global.fs = fs;
global.models = models;
global.response = response;
global.middleware = middleware;
global.slugify = slugify;
global.appErr = appErr;
global.cloudinary = cloudinary;
global.userHelper = userHelper;
global.StatusCodes = StatusCodes;
global.rateLimiter = rateLimiter;
global.hashPassword = hashPassword;
